# Generated by Django 3.0.5 on 2020-08-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
